# Generated by Django 5.0.6 on 2025-01-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio_app', '0002_alter_project_image_alter_skill_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
