# Generated by Django 5.0.6 on 2025-01-27 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio_app', '0003_alter_project_image_alter_skill_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
